version: "3"
services:
  db:
    container_name: mysql
    image: mysql:latest
    platform: linux/amd64
    restart: on-failure:3
    environment:
      MYSQL_ROOT_PASSWORD: root
      # MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_DATABASE: peppol_builder
      TZ: "Asia/Tokyo"
    command: --default-authentication-plugin=mysql_native_password
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_general_ci
      --explicit_defaults_for_timestamp=true
    volumes:
      - ./db-data:/usr/src/app
      - ./db-data/mysqld.cnf:/etc/mysql/mysql.conf.d/mysqld.cnf
      - ./db-data/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "3306:3306"
    networks:
      - backend
  app:
    tty: true
    build: .
    ports:
      - "8888:5000"
    env_file: .env
    depends_on:
      - db
    volumes:
      - .:/usr/src/app
    # command: flask run
    networks:
      - backend
networks:
  backend:
